name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # azd required
      AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # App secrets
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      # App config
      LANGCHAIN_PROJECT: ${{ secrets.LANGCHAIN_PROJECT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_SCHEMA: ${{ secrets.POSTGRES_SCHEMA }}
      MONGODB_HOST: ${{ secrets.MONGODB_HOST }}
      MONGODB_PORT: ${{ secrets.MONGODB_PORT }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "${{ secrets.AZURE_CLIENT_ID }}" `
            --federated-credential-provider "github" `
            --tenant-id "${{ secrets.AZURE_TENANT_ID }}"
        shell: pwsh

      - name: Provision and Deploy
        run: azd up --no-prompt
